language: c

script: 
    - ./maker ms/ms.html

before_install:
    - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
    - chmod 755 ./travis-tool.sh
    - ./travis-tool.sh bootstrap
    - ./travis-tool.sh install_github richfitz/maker
    - Rscript -e 'maker::install_maker(".")'
install:
    - ./maker install_packages

after_success:
    - cat ms/ms.html
