language: c

script:
    - ./remake ms/ms.md

before_install:
    - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
    - chmod 755 ./travis-tool.sh
    - ./travis-tool.sh bootstrap
    - ./travis-tool.sh install_github richfitz/remake
    # this one is in Suggests, so not always added.
    - ./travis-tool.sh install_r optparse
    - Rscript -e 'remake::install_remake(".")'

install:
    - Rscript -e 'options(repos="http://cran.rstudio.com"); remake::install_missing_packages()'

after_success:
    - cat ms/ms.md

notifications:
  slack: bdkd:hY2eBCaH3bbsvNwlWwOfFdfr
