language: r
latex: false
dist: trusty
cache: packages
warnings_are_errors: false

notifications:
  email:
    on_success: change
    on_failure: change

install:
  - R -e 'install.packages("devtools")'
  - R -e 'devtools::install_github("richfitz/storr")'
  - R -e 'devtools::install_github("richfitz/remake")'
  - R -e 'remake::install_missing_packages()'

script:
  - R -e 'remake::make("export")'

notifications:
  slack: bdkd:vj80qn6ZugIB1Uh4p6MBrkVq
