init:
  ps: |
        Get-Date
        $ErrorActionPreference = "Stop"
install:
  ps: |
        Import-Module '.\scripts\appveyor-tool.ps1'
        Bootstrap
cache:
  - C:\RLibrary

build_script:
  - travis-tool.sh install_github richfitz/storr
  - travis-tool.sh install_github richfitz/remake
  - Rscript -e 'remake::install_remake(".")'
  - Rscript -e 'options(repos="http://cran.rstudio.com"); remake::install_missing_packages();'

test_script:
  - Rscript -e 'remake::make("export");'

on_failure:
  - travis-tool.sh dump_logs

environment:
  global:
    USE_RTOOLS: true
